### ISSUE TITLE
edit list of customers

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#18]
aim:
the user has to have the possibility to manage the customers

now:
no user has the possibility to manage the customers

**Comment by starkbaum** [comment]
done

**Comment by kra16589** [comment]
when i select one customer for editing, I receive an error page
![image](https://cloud.githubusercontent.com/assets/9113015/13555315/a7bd7d1c-e3bd-11e5-974a-e76234f22102.png)

**Comment by kra16589** [comment]
pushed controller for this list --> OK
