### ISSUE TITLE
display issue English word -> German

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#20]
At "add customer" in the predefined line "ZIP code" is displayed

objective:
there should be "PLZ" bzw. "Postleitzahl" angezeigt werden

[http://sucon.dev/customers/create](url)

![image](https://cloud.githubusercontent.com/assets/9113015/13499863/4729695c-e160-11e5-9bf5-c62b9ccc791a.png)

**Comment by starkbaum** [comment]
done
