### ISSUE TITLE
odering of customer list

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#22]
description:
the overview is by an internal id or time of adding

objective:
the list should be sorted - my suggestion by name; no need for other possibilities

[http://sucon.dev/customers?page=10](url)
![image](https://cloud.githubusercontent.com/assets/9113015/13500226/e64d8cf6-e161-11e5-9ad4-9687c58f2990.png)

**Comment by starkbaum** [comment]
at the moment not possible with framework methods, i will try later with javascript

**Comment by kra16589** [comment]
skip it!!
