### ISSUE TITLE
on the left side-bar the SEARCH has to be removed

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#25]
description:
on the left side-bar a search is selectable - @starkbaum: for dev issues

objective:
remove this SEARCH

[http://sucon.dev/search](url)

![image](https://cloud.githubusercontent.com/assets/9113015/13500704/e992391e-e163-11e5-9fa6-3a6d4e04f117.png)

**Comment by starkbaum** [comment]
done
