### ISSUE TITLE
Snippets view is not working proper

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#26]
description:
after adding one snippet, the overview wasn't available any more

objective:
snippets should work in proper way

![image](https://cloud.githubusercontent.com/assets/9113015/13501268/42c84026-e166-11e5-9f99-f56afd220c39.png)

![image](https://cloud.githubusercontent.com/assets/9113015/13501275/4ad1cbac-e166-11e5-988f-07f49a2322fd.png)

**Comment by starkbaum** [comment]
i cant reproduce this error :(

**Comment by kra16589** [comment]
![image](https://cloud.githubusercontent.com/assets/9113015/13555257/ca773638-e3bb-11e5-88df-c0fbcc8dd1d1.png)

--> Freigabe anfordern

Resultat:
![image](https://cloud.githubusercontent.com/assets/9113015/13555259/dc8f8168-e3bb-11e5-89b7-702503e879ed.png)

**Comment by starkbaum** [comment]
done
