### ISSUE TITLE
Snippets -> search

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#31]
description:
After seraching a snippet, the result displays "SEARCHTERM" in the line and the snippets are displayed as like courses.

![image](https://cloud.githubusercontent.com/assets/9113015/13555273/4c7096ca-e3bc-11e5-8ed0-517dad81ed56.png)

When selecting one snippets, an error page is displayed

![image](https://cloud.githubusercontent.com/assets/9113015/13555276/602e7d6c-e3bc-11e5-8af9-6d22b62b7cea.png)

objective:
1. The "real" searchterm should be displayed not the name of the attribute
2. the results shall be displayed like the snippets or the main view of the snippets shall be adapted
3. the selected snippet shall be displayed when selected when it has been searched

**Comment by starkbaum** [comment]
done
