### ISSUE TITLE
create snippet

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#33]
issue:
when creating a snippet with coding language(s) and keywords the user receives an error page

![image](https://cloud.githubusercontent.com/assets/9113015/13571156/5d44c7fc-e473-11e5-955d-78e55c2718c2.png)

objective:
when creating a snippet there is no need for coding language and keyword - remove this.

![image](https://cloud.githubusercontent.com/assets/9113015/13571172/7baff0e0-e473-11e5-9746-f6b23bf2ea7d.png)

![image](https://cloud.githubusercontent.com/assets/9113015/13571147/57127d2a-e473-11e5-93e1-ca58df30df82.png)

**Comment by starkbaum** [comment]
done
