### ISSUE TITLE
change display when no video available

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#37]
description:
when a course has no video an error message is displayed

![image](https://cloud.githubusercontent.com/assets/9113015/13751437/75bbbd9e-ea0a-11e5-8c5c-9c5167a7485a.png)

objective:
when no video is refered to a course no error message should be displayed. Display a text or nothing

**Comment by starkbaum** [comment]
should not be the case

//fetches all Videos
        $videos = Data::where('extension', 'AVI')->orWhere('extension', 'avi')->orWhere('extension', 'mp4')->get();

and check in view

@if( !$videos->isEmpty() )

maybe there is a video in your database?
