### ISSUE TITLE
adding a video to a course, first frame remains

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#38]
desription:
when user is adding a film to a course the first frame with the error message remains in the overview and can be selected

part one
![image](https://cloud.githubusercontent.com/assets/9113015/13751607/3d6c3616-ea0b-11e5-8d9c-98b29ba8e2bf.png)

part two
![image](https://cloud.githubusercontent.com/assets/9113015/13751632/50d01204-ea0b-11e5-862d-4e568f77f648.png)

objective:
the first "part" should be removed when adding the first movie

**Comment by starkbaum** [comment]
maybe related to #37
