### ISSUE TITLE
display hint at buttons

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#45]
description:
at KUNDEN -> Details of KUNDEN no hints are displayed at the buttons

![image](https://cloud.githubusercontent.com/assets/9113015/13818982/38add68c-eb98-11e5-80c2-ebdc7b84dece.png)

like:
![image](https://cloud.githubusercontent.com/assets/9113015/13818864/d9c60036-eb97-11e5-82ec-0d608a5eef7a.png)

objective:
add "hints" to the main buttons

**Comment by starkbaum** [comment]
done
