### ISSUE TITLE
mail-to doesn't work in snippet and course

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#51]
descritpion:
mail-to "send" --> user receives error page

@snippet:
![image](https://cloud.githubusercontent.com/assets/9113015/13873797/271292e8-ecf4-11e5-868d-e1997b560b89.png)

@course:
![image](https://cloud.githubusercontent.com/assets/9113015/13873954/1c9d8e20-ecf5-11e5-97ff-86d68b87a9d6.png)

obejctive:
mail-to has to work

**Comment by starkbaum** [comment]
please check mail. maybe a problem with .env file

**Comment by kra16589** [comment]
done; add data in env...
