### ISSUE TITLE
no possibility to delete a file in a course

### ISSUE THREAD

**Issue by kra16589** [starkbaum/sucon#52]
description:
the user(admin) has no possibility to delete a file in a course; a file in a snippet is deleteable

![image](https://cloud.githubusercontent.com/assets/9113015/13873836/6a979806-ecf4-11e5-86b5-4cb9bf10215a.png)

like in snippets:
![image](https://cloud.githubusercontent.com/assets/9113015/13873887/bad40eee-ecf4-11e5-91dd-5ff4f5a2791b.png)

objective:
user(admin) should have the possibility to delete files

**Comment by starkbaum** [comment]
has your user really admin rights?

**Comment by starkbaum** [comment]
done
